[package]
name = "routerosbackuptools"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.60"
binread = "2.1.1"
binwrite = "0.2.1"
clap = "3.2.16"
hmac = "0.12.1"
rand = "0.8.4"
rayon = "1.5.1"
rust-crypto = "0.2.36"
sha-1 = "0.10.0"
sha2 = "0.10.2"
