[package]
name = "routerosbackuptools"
version = "0.1.2"
edition = "2021"

[dependencies]
aes = "0.8.1"
anyhow = "1.0.65"
binread = "2.2.0"
binwrite = "0.2.1"
clap = "3.2.22"
ctr = "0.9.2"
hmac-sha256 = "1.1.4"
rand = "0.8.5"
rayon = "1.5.3"
rc4 = "0.1.0"
sha-1 = "0.10.0"
sha2 = "0.10.6"
