[package]
authors = ["marcograss"]
description = "Tool to encrypt/decrypt and pack/unpack RouterOS v6.13+ backup files"
edition = "2021"
name = "routerosbackuptools"
version = "0.1.3"

[dependencies]
aes = "0.8.2"
anyhow = "1.0.66"
binread = "2.2.0"
binwrite = "0.2.1"
clap = "4.0.18"
ctr = "0.9.2"
hmac-sha256 = "1.1.5"
rand = "0.8.5"
rayon = "1.5.3"
rc4 = "0.1.0"
sha-1 = "0.10.0"
sha2 = "0.10.6"
