[package]
name = "routerosbackuptools"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "2.1.1"
binwrite = "0.2.1"
clap = "2.33.3"
hmac = "0.11.0"
rand = "0.8.4"
rayon = "1.5.1"
rust-crypto = "0.2.36"
sha-1 = "0.9.7"
sha2 = "0.9.5"
